### ISSUE TITLE
Package errors out when adding `@codepen` tag to inline block documentation.

### ISSUE THREAD

**Issue by HTMLGhozt** [bit-docs/bit-docs-html-codepen-link#1]
__How often can you reproduce it?__ 
- [x] Always

__Description:__
Package errors out when adding `@codepen` tag to inline block documentation.

```
ERROR:
   tag - codepen
   line- @codepen
/Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property 'codepen' of undefined
    at Object.add (/Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-html-codepen-link/tags.js:11:31)
    at module.exports (/Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-process-tags/process-tags.js:95:29)
    at /Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-js/process/code_and_comment.js:41:4
    at module.exports (/Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-js/process/code.js:42:2)
    at module.exports (/Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-js/process/code_and_comment.js:40:3)
    at /Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-js/process/javascript.js:26:13
    at Array.map (<anonymous>)
    at module.exports (/Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/configure/node_modules/bit-docs-js/process/javascript.js:25:29)
    at /Users/bitovi/Documents/bitovi/canjs/node_modules/bit-docs/lib/process/file.js:80:17
    at Array.some (<anonymous>)
```

__Steps to reproduce:__

- Detail the exact steps taken to produce the problem
Attempted to add `@codepen` tag to [a can-define/list/list example](https://github.com/canjs/can-define/blob/master/list/list.js#L188-L191). Running `./node_modules/.bin/bit-docs` causes the error above.

- Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
![example](https://user-images.githubusercontent.com/12449668/44542743-8d57ae00-a6c2-11e8-8704-16b89411b9c4.gif)

__Expected results:__
Successfully ink to codepen and generate documentation properly.

__Environment:__

| Software                   | Version
| -------------------- | -------
| bit-docs-html-codepen-link version   | 1.2.1 
| Browser                    | 
| Operating system    | Mac 10.13.6

**Comment by HTMLGhozt** [comment]
It seems to be referencing this [line in bit-docs-html-codepen-link](https://github.com/bit-docs/bit-docs-html-codepen-link/blob/master/tags.js#L11).

Changing that line to what's below prevents the error, but still provides unexpected results:
```js
if(options.siteConfig && options.siteConfig.codepen) {
    this.codepen = options.siteConfig.codepen;
}
```

*unexpected results*
![example_2](https://user-images.githubusercontent.com/12449668/44543449-6a2dfe00-a6c4-11e8-8000-9683a96e49ac.gif)

**Comment by HTMLGhozt** [comment]
After further testing:
```js
if(options.siteConfig && options.siteConfig.codepen) {
    this.codepen = options.siteConfig.codepen;
}
```
Fixes the issue with proper tabbing.
